### ISSUE TITLE
Dsvpn docker cannot start

### ISSUE THREAD

**Issue by Youngv** [cofyc/dsvpn-docker#3]
#### system:
ubuntu 16.04

#### command
```bash
dd if=/dev/urandom of=vpn.key count=1 bs=32

~/dsvpn $ docker run --name dsvpn.service --network host --privileged -v ~/dsvpn/vpn.key:/etc/dsvpn.key cofyc/dsvpn:latest server /etc/dsvpn.key auto 443
```
#### result
![image](https://user-images.githubusercontent.com/1787625/68911019-a6002800-078e-11ea-92bb-7c3cd601ec17.png)

####  docker logs output
> net.ipv4.ip_forward = 1

**Comment by cofyc** [comment]
hi, this docker command runs the process in the foreground. `net.ipv4.ip_forward = 1` is not an error message. Does it fail immediately?  

Alternatively, you can run it in daemon mode by adding `-d` flag, e.g.

```
$ docker run -d --name dsvpn.service --network host --privileged -v ~/dsvpn/vpn.key:/etc/dsvpn.key cofyc/dsvpn:latest server /etc/dsvpn.key auto 443
b2c2b4887a65ddf307ee800d81150149fee0eb7cc8496655119f7a5d6b9bbdf9
$ ps -C dsvpn -opid,args
   PID COMMAND
 68860 /usr/local/bin/dsvpn server /etc/dsvpn.key auto 443
```

**Comment by Youngv** [comment]
It fail immediately, add `-d` fail still, make from source code works fine
```
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                       PORTS                                                                                                NAMES
6809d32d9028        cofyc/dsvpn:latest                     "/usr/local/bin/dsvp…"   7 seconds ago       Exited (132) 4 seconds ago                                                                                                        dsvpn.service
```

**Comment by cofyc** [comment]
ah, I'll take a look at this issue.

**Comment by cofyc** [comment]
@Youngv what's your docker version and kernel version?

`docker version` and `uname -a`

**Comment by Youngv** [comment]
```
root@VICTOR:~ $ docker -v
Docker version 18.09.3, build 774a1f4
root@VICTOR:~ $ uname -a
Linux VICTOR 4.9.151-0409151-generic #201901161743 SMP Wed Jan 16 22:47:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cofyc** [comment]
can you paste the full output of this command `docker run -d --name dsvpn.service --network host --privileged -v ~/dsvpn/vpn.key:/etc/dsvpn.key cofyc/dsvpn:latest server /etc/dsvpn.key auto 443` and container logs via `docker logs dsvpn.service`?

note that, you need to remove previous container via `docker rm -f dsvpn.service`

**Comment by Youngv** [comment]
```
root@VICTOR:~/dsvpn $ docker run -d --name dsvpn.service --network host --privileged -v ~/dsvpn/vpn.key:/etc/dsvpn.key cofyc/dsvpn:latest server /etc/dsvpn.key auto 443
a1bb9ebfcc2256bffa47494872530d9d98267d2d4e939ead67e39d9fd9dbc7a6
root@VICTOR:~/dsvpn $ docker logs dsvpn.service
net.ipv4.ip_forward = 1
root@VICTOR:~/dsvpn $ docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                        PORTS                                                                                                NAMES
a1bb9ebfcc22        cofyc/dsvpn:latest                     "/usr/local/bin/dsvp…"   13 seconds ago      Exited (132) 12 seconds ago                                                                                                        dsvpn.service
```

**Comment by Youngv** [comment]
I have another containers running, but not on 443 port, does that matter?

**Comment by cofyc** [comment]
it didn't print any useful messages...

will other containers touch routes/iptables on the server? if they will, they may conflict because dsvpn need to create tun device and set up some routes/iptables.

**Comment by Youngv** [comment]
@cofyc I build the image from your dockerfile and works fine, but not work from the image on docker hub, Is there something different?

**Comment by cofyc** [comment]
it should be the same, the only difference is at different build times, the dsvpn source on the master branch is different because you're using the latest tag.
